services:
  trafik:
    build: .
    container_name: trafik
    restart: "no"
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
      - ./camera_config.json:/app/camera_config.json:ro
      - ./vms_config.json:/app/vms_config.json:ro
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"
